# Generated by Django 3.0.5 on 2021-06-21 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='marks',
            new_name='mark',
        ),
        migrations.RemoveField(
            model_name='course',
            name='question_number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.RemoveField(
            model_name='result',
            name='date',
        ),
    ]
